### ISSUE TITLE
Random build failures due to fs-extra defect

### ISSUE THREAD

**Issue by oliversalzburg** [apache/cordova#121]
# Bug Report

### What is expected to happen?
You are able to build your Cordova project reliably.

### What does actually happen?
Builds randomly fail with the error **Source and destination must not be the same.**

## Information
The random failures are caused by a [defect in fs-extra](https://github.com/jprichardson/node-fs-extra/issues/657), which neglects to respect an inode-related issue in Node itself.

### Command or Code
Every command that copies files with `fs-extra` is affected. `cordova prepare` is most likely to cause this.

### Environment, Platform, Device
Windows 10

### Version information
Cordova 8.1.2 (cordova-lib@8.1.1)

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by brodybits** [comment]
I just transferred this issue from cordova-common to cordova and closed #83 as a duplicate. Also discussed in the following places:

- <https://github.com/apache/cordova-lib/pull/613#issuecomment-474377440>
- apache/cordova-android#692 / apache/cordova-android#693
- proposed bugfix on cordova-common in apache/cordova-common#70

I hope to get the bugfix on cordova-common released next week, then I think we should update some other packages including cordova-lib, cordova-android, cordova-windows, and cordova-cli.

Please feel free to contact us via email to <dev@cordova.apache.org> in case of any further delays.

**Comment by ath0mas** [comment]
cordova-common@3.2.0 is now released with apache/cordova-common#70 merged (Thx! @brodybits)
Will it be available in Npm soon? With updates of the other packages you mentioned too?

**Comment by brodybits** [comment]
> (Thx! @brodybits)

You are welcome.

> Will it be available in Npm soon?

I am still waiting for one more vote from a committer, will publish on npm on Friday if we get the vote in time.

> With updates of the other packages you mentioned too?

I only mentioned some other issues and a PR where a similar problem was reported.

I think the update in `cordova-common` should resolve the issue for cordova-android and cordova-windows platforms since they do not use any other Cordova dependencies.

I would also like to apply the same update to some other Cordova packages, cannot promise when I will have time to do this. Here are the packages I think should be updated when someone gets a chance:

- `cordova-electron`
- `cordova-create`
- `cordova-fetch`
- `cordova-lib`
- `cordova-windows` - update should be done in `devDependencies`, which should only affect end-to-end test script and **not** any end users

**Comment by brodybits** [comment]
I just published cordova-common@3.2.0 on npm, blog post should show up pretty soon. I expect that this should resolve the reported issue for most if not all users. Here is the recommended procedure to update both the Cordova tooling and Cordova project:

- remove existing installation of Cordova by the following command: `npm uninstall -g cordova`, or use a manager such as nvm or the cross-platform [`jasongin/nvs`](https://github.com/jasongin/nvs) to start with a fresh new installation of Node.js
- install Cordova tooling again by the following command: `npm install -g cordova`
- in the Cordova app project:
  - do the following command for each platform: `cordova platform rm <platform name>`
  - completely remove the following artifacts: `package-lock.json`, `node_modules`, and `platforms` directory
  - it is optional but recommended to completely remove the `plugins` directory as well
  - double-check that there is no remaining configuration of `cordova-common` or any of the Cordova platforms in `config.xml` or `package.json`
  - try adding and building for each desired platform, as documented

This may be extra pedantic, but I would recommend this procedure to hopefully ensure a zero chance of using an old version of `cordova-common`.

I would like to update the other packages (`cordova-create`, `cordova-fetch`, `cordova-lib`, `cordova-electron`, and `cordova-windows`) to use fs-extra@8. Unfortunately I cannot promise when I will get a chance to work on these.

I took about 2-3 days out of an extremely busy schedule to make this update, in response to the demand from the user community.

**Comment by l3ender** [comment]
Thanks much, @brodybits!

> I would like to update the other packages (`cordova-create`, `cordova-fetch`, `cordova-lib`, `cordova-electron`, and `cordova-windows`) to use fs-extra@8. Unfortunately I cannot promise when I will get a chance to work on these.

Is there any way I could help out in updating other packages? Would you like me to submit PRs targeting the updated packages?

I see that the above packages have dependencies to both `cordova-common` and `fs-extra`. How come `fs-extra` is explicitly mentioned instead of being pulled in as a transitive dependency of `cordova-common`?

Again, thanks for your efforts!

**Comment by sayanjyotidas** [comment]
I have fixed the problem (for my Cordova build not working) by a much easier way guys. Please follow the below steps to update your `cordova-common` library without having to re-install Cordova or `cordova-android`:

- Clone the latest (bug-fixed) `cordova-common` repository to your machine by runing `git clone https://github.com/apache/cordova-common.git`

- `cd` to the cloned directory and run `npm install` to download the required dependencies.

- After you have completely installed the library along with dependencies, cut (or copy) the entire `cordova-common-master` folder (the directory which you just downloaded) and paste in into `<your cordova project>/node_modules` folder, be sure to replace the previous outdated `cordova-common` directory.

- Restart your CLI and the cordova build should work fine :-)

**Comment by Perh0rd** [comment]
I want to add that if problem persist for Windows 10 users, just follow these steps : 

- Upgrade node.js : https://nodejs.org/en/download/

- Upgrade npm by launching a powershell (as admin) and the following commands : 
```Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force```
```npm install -g npm-windows-upgrade```
```npm-windows-upgrade````

This worked for me.

**Comment by vienom** [comment]
Hi!

I'm facing the same issue and I'm building on a mac.
cordova-common: 3.2.0
fs-extra: 8.1.0

Android (8.0.0) and iOS (5.0.1) builds fail.

**Comment by brodybits** [comment]
> I'm facing the same issue and I'm building on a mac.

Which version of Node.js are you using?

I would *highly* recommend using the latest patch on Node.js version 10.

**Comment by vienom** [comment]
My node version is 10.15.3

**Comment by jamesdixon** [comment]
This issue continuously kills me and does so at random...

**Comment by gquagliano** [comment]
This may be caused by symlinks, at least that was my case. The solution, other than upgrading as stated before, is to replace symbolic links with hard links.

**Comment by I-Connect** [comment]
@gquagliano  thx for this trigger, this solved it (Source and destination must not be the same.) for me when adding a new platform.

I use a virtualbox for development and I have disks mapped as network share from my host where the projects are located.

Moving the cordova project to the C drive fixed it for me.

**Comment by Stredsto** [comment]
is it issue still active/open ?

**Comment by Stredsto** [comment]
is this issue still open ?

**Comment by breautek** [comment]
Closing this issue as obsolete. If you still have this issue, I'd recommend trying to reinstalling cordova and/or clearing your package-lock & node_modules to force npm to fetch the latest satisfactory dependencies, which should include the fixes from fs-extra upstream.
