### ISSUE TITLE
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer

### ISSUE THREAD

**Issue by Yowsifahamed** [apache/cordova#14]

**Comment by raphinesse** [comment]
Already resolved in master

**Comment by sielimsky** [comment]
Hey @raphinesse. I'm glad it is solved - sadly, Today I'm getting the same warning. So a question - from a newbie - what do you mean by "resolved" in master? Hoek package version is 5.0.4... I think.

**Comment by raphinesse** [comment]
We already resolved this issue in the latest development version of Cordova. However, the fix has not yet been included in a *release* of Cordova. That's why you still see the warning. However, there's nothing more to do than wait for the next release.

**Comment by turtle0001** [comment]
Thanks guys!

May I asked when do you plan to release the fix? thanks! :)

**Comment by raphinesse** [comment]
The release process for 8.1.0 will start today. That means you can expect the release in the first half of this week if there are no issues with it.

**Comment by Yowsifahamed** [comment]
pleasure see this news

**Comment by turtle0001** [comment]
Thank you guys for doing this! Appreciate it! :)
